sudo: required
services:
  - docker

before_install:
  - docker build -t abhinavroy23/complex_client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abhinavroy23/complex_client npm test --coverage

after_success:
  - docker build -t abhinavroy23/docker-multi-client ./client
  - docker build -t abhinavroy23/docker-multi-nginx ./nginx
  - docker build -t abhinavroy23/docker-multi-server ./server
  - docker build -t abhinavroy23/docker-multi-worker ./worker
  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push to docker hub
  - docker push abhinavroy23/docker-multi-client
  - docker push abhinavroy23/docker-multi-nginx
  - docker push abhinavroy23/docker-multi-server
  - docker push abhinavroy23/docker-multi-worker
